import Head from "next/head";
import { useRouter } from "next/router";
import ModeSetting from "./ModeSetting";

const Header = () => {
  const router = useRouter();
  const PageTitle = router.query.name;
  return(
    <>
      <Head>
        <title>DONMIT {PageTitle !== null ? " | " +PageTitle : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header_bar">
        <ul className="flex flex_jc_sb flex_basis_100">
          <li className="logo">
            여기는 로고가 들어가겠죠? 아마도 그렇겠죠?
          </li>
          <li title="이건 프로젝트 다크모드버튼입니다. 일단 만들어놨어요. 퍼블은 나중에!">
            <ModeSetting/>
          </li>
        </ul>
      </header>   
    </>
  )
}

export default Header;