import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DONMIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Front Source</div>
      <Link
        href={{ pathname: `group/Group`, query: { name: "DONMIT_GROUP" } }}
        as={"group/Group"}
      >
        Test Link (그룹명 : DONMIT_GROUP)
      </Link>
    </>
  );
}
