import Head from "next/head";

const Header = () => {
  return(
    <>
      <Head>
        <title>DONMIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header_bar">
        
      </header>   
    </>
  )
}

export default Header;